name: FS-SpigotCore
main: com.forgestorm.spigotcore.SpigotCore
version: 0.1.5
description: ForgeStorm SpigotCore
author: unenergizer aka Robert Andrew Brown
website: http://www.forgestorm.com/
depend: [TitleManager]
commands:
   admin:
   creative:
   compass:
   lantern:
   help:
   mainmenu:
   settings:
   mod:
   money:
      aliases: [bal, balance, gems]
   playtime:
      aliases: [pt]
   roll:
   safestop:
   worldanimate:
      aliases: [wa]